
parameters:
  wx_config:
    debug: true
    app_id: your-app-id
    secret: your-app-secret
    token: your-token
    aes_key: ''
    log:
      level: debug
      permission: 511
      file: "/tmp/easywechat.log"
    oauth:
      scopes:
      - snsapi_userinfo
      callback: "/examples/oauth_callback.php"
    payment:
      merchant_id: your-mch-id
      key: key-for-signature
      cert_path: path/to/your/cert.pem
      key_path: path/to/your/key
    guzzle:
      timeout: 3
