botmm_buffer:
    resource: "@botmmBufferBundle/Controller/"
    type:     annotation
    prefix:   /buffer

botmm_client:
    resource: "@botmmClientBundle/Controller/"
    type:     annotation
    prefix:   /client

botmm_gradee:
    resource: "@botmmGradeeBundle/Controller/"
    type:     annotation
    prefix:   /gradee

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
