botmm_buffer:
    resource: "@botmmBufferBundle/Resources/config/routing.php"
    prefix:   /

botmm_client:
    resource: "@botmmClientBundle/Resources/config/routing.php"
    prefix:   /

botmm_gradee:
    resource: "@botmmGradeeBundle/Resources/config/routing.php"
    prefix:   /

inspect_containter:
    resource: "@InspectContainterBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
