<?php

namespace Inspect\ContainterBundle\Repository;

use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Query\Expr;

/**
 * NewsRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTitle()
    {
        return 'yse';
    }

    public function getName()
    {
        $criteria = new Criteria(new Expr());
        $this->createQueryBuilder('n')
            ->addCriteria();
    }
}
